wrong_password = "Wrong password"
invalid_username = "The selected username is invalid"
invalid_token = "The header token is invalid"
token_required = "The token is required with the request"
token_not_required = "The token is not required with the request"
item_is_not_found = "Item is not found"
the_selected_id_is_not_found = "The selected id is not found"
invoke_services = "The list has relations with other services please revoke them first"